version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3010:3010'
    environment:
      NODE_ENV: production
